apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grabtable

resources:
- namespace.yaml
- secret.yaml
- ../../../base/be

images:
- name: harbor.k8s.scg.skku.ac.kr/library/grabtable-be
  newTag: local2
