apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grabtable

resources:
- namespace.yaml
- secret.yaml
bases:
  - ../../../base/be


patches:
- path: domain.json
  target:
    kind: Ingress
    name: grabtable-be-ingress
images:
- name: harbor.k8s.scg.skku.ac.kr/library/grabtable-be
  newTag: de5d5d89f7714b2c58e51be582d39366925f1e44
