apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grabtable
patchesStrategicMerge:
- ingress.yaml
- secret.yaml
- deployment.yaml
resources:
- ../../../base/fe
images:
- name: harbor.k8s.scg.skku.ac.kr/library/grabtable-fe
  newTag: 45ea65b6e9e1968195a1aafe1bf05cfdd515ce68
