apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grabtable
resources:
- secret.yaml
- ../../../base/fe

patches:
- path: domain.json
  target:
    kind: Ingress
    name: grabtable-fe-ingress
- path: deployment.json
  target:
    kind: Deployment
    name: grabtable-fe-deployment

images:
- name: harbor.k8s.scg.skku.ac.kr/library/grabtable-fe
  newTag: latest
