apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grabtable
patchesStrategicMerge:
- ingress.yaml

resources:
- ../../../base/fe
images:
- name: harbor.k8s.scg.skku.ac.kr/library/grabtable-fe
  newTag: latest