apiVersion: v1
kind: Secret
metadata:
  name: grabtable-secret
type: Opaque
data:
  SESSION_SECRET: <path:kv/data/grabtable-secret#session-secret | base64encode>
  NEXT_PUBLIC_KAKAO_CLIENT_ID: <path:kv/data/grabtable-secret#kakao-client | base64encode>
  NEXT_PUBLIC_KAKAO_REDIRECT_URI: <path:kv/data/grabtable-secret#redirect-uri | base64encode>
  NEXT_PUBLIC_KAKAO_MAP_KEY: <path:kv/data/grabtable-secret#kakao-map | base64encode>
  BASE_API_URL: <path:kv/data/grabtable-secret#api-url | base64encode>
  BASE_URL: <path:kv/data/grabtable-secret#base-url | base64encode>